/**
 * Design reminder — Retail Operations Ledger:
 * Dense, calm work surfaces present live POS data and reserve amber for commercial attention.
 */
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";
import {
  ArrowDownRight,
  ArrowUpRight,
  Bell,
  Boxes,
  CalendarDays,
  Check,
  ChevronDown,
  CircleDollarSign,
  ClipboardList,
  CreditCard,
  Download,
  ExternalLink,
  FileBarChart,
  Filter,
  Globe2,
  Landmark,
  Loader2,
  Minus,
  MoreHorizontal,
  PackageCheck,
  Pencil,
  Plus,
  ReceiptText,
  Search,
  ShoppingBag,
  SlidersHorizontal,
  Store,
  Tag,
  Trash2,
  Truck,
  Upload,
  UsersRound,
  WalletCards,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { useShop } from "@/contexts/ShopContext";

type ProductRecord = { id: number; name: string; sku: string; category: string; price: string; stock: number };
type ValueMap = Record<string, string>;
type DialogField = { key: string; label: string; type?: "text" | "email" | "number"; options?: string[]; placeholder?: string };

const productFields: DialogField[] = [
  { key: "name", label: "Product name", placeholder: "e.g. Apple Earbuds" },
  { key: "sku", label: "SKU", placeholder: "e.g. TC-1024" },
  { key: "category", label: "Category", placeholder: "e.g. Audio" },
  { key: "price", label: "Price (EUR)", type: "number", placeholder: "0.00" },
  { key: "stock", label: "Units in stock", type: "number", placeholder: "0" },
];

function PageHeader({ eyebrow, title, detail, actions }: { eyebrow: string; title: string; detail: string; actions?: ReactNode }) {
  return <section className="workspace-header panel-reveal"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{detail}</p></div>{actions ? <div className="page-actions">{actions}</div> : null}</section>;
}

function Surface({ title, kicker, action, children, className = "" }: { title: string; kicker?: string; action?: ReactNode; children: ReactNode; className?: string }) {
  return <article className={`workspace-surface ${className}`}><div className="surface-heading"><div>{kicker ? <p className="card-kicker">{kicker}</p> : null}<h2>{title}</h2></div>{action}</div>{children}</article>;
}

function MiniMetric({ label, value, trend, tone = "green" }: { label: string; value: string; trend: string; tone?: "green" | "amber" | "blue" }) {
  return <div className="mini-metric"><p>{label}</p><strong>{value}</strong><span className={`mini-trend mini-trend--${tone}`}>{tone === "amber" ? <ArrowDownRight /> : <ArrowUpRight />}{trend}</span></div>;
}

function StatusPill({ children, tone = "green" }: { children: ReactNode; tone?: "green" | "amber" | "red" | "blue" }) { return <span className={`status-pill status-pill--${tone}`}>{children}</span>; }

function productTone(label: string) {
  const tones = ["#f5b73a", "#2d88df", "#20bd87", "#e56464", "#7d68d8", "#46b5a6"];
  return tones[label.length % tones.length];
}

function ProductArt({ product }: { product: Pick<ProductRecord, "name"> }) { return <div className="product-art" style={{ background: `linear-gradient(145deg, ${productTone(product.name)} 0%, #ffffff 118%)` }}><PackageCheck /></div>; }

function EntityDialog({ open, onOpenChange, title, detail, fields, initial = {}, onSubmit, submitting }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; detail: string; fields: DialogField[]; initial?: Record<string, unknown>; onSubmit: (values: ValueMap) => void; submitting?: boolean }) {
  const [values, setValues] = useState<ValueMap>(() => Object.fromEntries(fields.map((field) => [field.key, String(initial[field.key] ?? "")])) as ValueMap);
  const submit = (event: React.FormEvent) => { event.preventDefault(); onSubmit(values); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="crud-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><p>{detail}</p></DialogHeader><form onSubmit={submit} className="crud-form">{fields.map((field) => <Label key={field.key}>{field.label}{field.options ? <select value={values[field.key] ?? ""} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} required><option value="" disabled>Select an option</option>{field.options.map((option) => <option key={option} value={option}>{option}</option>)}</select> : <Input type={field.type ?? "text"} min={field.type === "number" ? 0 : undefined} step={field.type === "number" ? "0.01" : undefined} value={values[field.key] ?? ""} placeholder={field.placeholder} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} required />}</Label>)}<div className="crud-dialog-actions"><button type="button" className="soft-button" onClick={() => onOpenChange(false)}>Cancel</button><Button className="dark-action" disabled={submitting} type="submit">{submitting ? <Loader2 className="animate-spin" /> : <Check />}{submitting ? "Saving" : "Save record"}</Button></div></form></DialogContent></Dialog>;
}

function EmptyState({ label, description }: { label: string; description: string }) { return <div className="data-empty"><Boxes /><b>{label}</b><span>{description}</span></div>; }
function LoadingState() { return <div className="data-empty"><Loader2 className="animate-spin" /><b>Loading workspace data</b><span>TradeCore is retrieving your latest records.</span></div>; }
function money(value: string | number) { return new Intl.NumberFormat("en-IE", { style: "currency", currency: "EUR" }).format(Number(value)); }
function dateLabel(value: Date | string) { return new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
function removeRecord(label: string, action: () => void) { if (window.confirm(`Delete ${label}? This cannot be undone.`)) action(); }
function LocationSelector({ locations, value, onChange }: { locations: Array<{ id: number; name: string }>; value?: number; onChange: (id: number) => void }) { return locations.length ? <label className="date-control"><Store aria-hidden="true" /><select value={value ?? ""} onChange={(event) => onChange(Number(event.target.value))} aria-label="Select active stock location"><option value="" disabled>Select location</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select><ChevronDown aria-hidden="true" /></label> : <span className="soft-button"><Store aria-hidden="true" /> No location yet</span>; }

export function POSPage() {
  const [cart, setCart] = useState<{ product: ProductRecord; qty: number }[]>([]);
  const [query, setQuery] = useState("");
  const { locations, activeShopId: locationId, setActiveShopId } = useShop();
  const productQuery = trpc.products.list.useQuery();
  const inventoryInput = useMemo(() => locationId ? { locationId } : undefined, [locationId]);
  const balanceQuery = trpc.inventory.balances.useQuery(inventoryInput);
  const utils = trpc.useUtils();
  const checkoutMutation = trpc.sales.checkout.useMutation({ onSuccess: () => { utils.sales.list.invalidate(); utils.products.list.invalidate(); utils.dashboard.summary.invalidate(); setCart([]); toast("Payment captured", { description: "The sale, payment, and stock movement were saved together in TradeCore." }); } });
  const stockByProductId = useMemo(() => new Map((balanceQuery.data ?? []).map((balance) => [balance.productId, balance.quantity])), [balanceQuery.data]);
  const catalog = (productQuery.data ?? []).map((product) => ({ ...product, price: String(product.price), stock: stockByProductId.get(product.id) ?? 0 }));
  const filtered = catalog.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()));
  const cartTotal = cart.reduce((sum, item) => sum + Number(item.product.price) * item.qty, 0);
  const count = cart.reduce((sum, item) => sum + item.qty, 0);
  const addProduct = (product: ProductRecord) => setCart((current) => { const found = current.find((item) => item.product.id === product.id); if (!product.stock || (found && found.qty >= product.stock)) { toast("Stock limit reached", { description: `${product.name} is not available in the selected location.` }); return current; } return found ? current.map((item) => item.product.id === product.id ? { ...item, qty: item.qty + 1 } : item) : [...current, { product, qty: 1 }]; });
  const adjust = (id: number, delta: number) => setCart((current) => current.flatMap((item) => item.product.id === id ? (item.qty + delta > 0 ? [{ ...item, qty: item.qty + delta }] : []) : [item]));
  const checkout = () => { if (!locationId) { toast("Choose a location", { description: "Select the store that will fulfil this sale." }); return; } checkoutMutation.mutate({ receiptNumber: `S-${Date.now().toString().slice(-7)}`, customerName: "Walk-in customer", channel: "Retail", paymentMethod: "Card", taxRate: 0.2, locationId, items: cart.map(({ product, qty }) => ({ productId: product.id, quantity: qty })) }); };
  return <div className="workspace-page pos-page"><PageHeader eyebrow="Counter workspace" title="Point of sale" detail="Build a basket, apply payment, and keep the counter moving." actions={<><LocationSelector locations={locations} value={locationId ?? undefined} onChange={(id) => { setActiveShopId(id); setCart([]); }} /><button className="soft-button" onClick={() => setCart([])}><ReceiptText /> Clear register</button><Button className="dark-action" onClick={() => toast("Register session opened", { description: "Counter 02 is synced and ready to trade." })}><Store /> Counter 02</Button></>} />
    <div className="register-layout panel-reveal"><Surface title="Catalog" kicker="Live product records" className="catalog-surface" action={<label className="inline-search"><Search /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" /></label>}><div className="catalog-filter"><button className="category-chip category-chip--active">All products</button><button className="category-chip">Audio</button><button className="category-chip">Home</button><button className="category-chip">Kitchen</button></div><div className="product-card-grid">{productQuery.isLoading ? <LoadingState /> : filtered.length ? filtered.map((product) => <button className="pos-product-card" key={product.id} onClick={() => addProduct(product)}><ProductArt product={product} /><span className="product-card-copy"><b>{product.name}</b><small>{product.stock} in stock</small><strong>{money(product.price)}</strong></span><span className="add-product"><Plus /></span></button>) : <EmptyState label="No catalog items yet" description="Add products in Product Manager, then they will appear here." />}</div></Surface>
      <Surface title="Current sale" kicker={`${count} item${count === 1 ? "" : "s"} in basket`} className="cart-surface" action={<button className="quiet-action" onClick={() => setCart([])}>Clear</button>}><div className="cart-lines">{cart.length ? cart.map(({ product, qty }) => <div className="cart-line" key={product.id}><ProductArt product={product} /><div><b>{product.name}</b><span>{money(product.price)} each</span></div><div className="quantity-stepper"><button aria-label={`Decrease ${product.name}`} onClick={() => adjust(product.id, -1)}><Minus /></button><b>{qty}</b><button aria-label={`Increase ${product.name}`} onClick={() => adjust(product.id, 1)}><Plus /></button></div></div>) : <div className="cart-empty"><ShoppingBag /><b>Your basket is empty</b><span>Select catalog items to begin this sale.</span></div>}</div><div className="cart-summary"><div><span>Subtotal</span><b>{money(cartTotal)}</b></div><div><span>Tax (20%)</span><b>{money(cartTotal * .2)}</b></div><div className="cart-total"><span>Total</span><b>{money(cartTotal * 1.2)}</b></div><Button className="checkout-button" disabled={!cart.length || checkoutMutation.isPending} onClick={checkout}>{checkoutMutation.isPending ? <Loader2 className="animate-spin" /> : <CreditCard />}{checkoutMutation.isPending ? "Capturing payment" : "Take payment"}</Button></div></Surface></div></div>;
}

export function ProductManagerPage() {
  const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<ProductRecord | null>(null); const [, navigate] = useLocation();
  const { activeShopId: locationId } = useShop();
  const productQuery = trpc.products.list.useQuery(); const utils = trpc.useUtils();
  const create = trpc.products.create.useMutation({ onSuccess: () => { utils.products.list.invalidate(); setOpen(false); toast("Product created", { description: "The item is now available in the POS catalog." }); } });
  const update = trpc.products.update.useMutation({ onSuccess: () => { utils.products.list.invalidate(); setOpen(false); setEditing(null); toast("Product updated", { description: "Catalog details have been saved." }); } });
  const remove = trpc.products.remove.useMutation({ onSuccess: () => { utils.products.list.invalidate(); toast("Product deleted", { description: "The record has been removed from the catalog." }); } });
  const items = (productQuery.data ?? []).map((product) => ({ ...product, price: String(product.price) })); const shown = items.filter((product) => product.name.toLowerCase().includes(search.toLowerCase()));
  const startCreate = () => { setEditing(null); setOpen(true); }; const startEdit = (product: ProductRecord) => { setEditing(product); setOpen(true); };
  const submit = (values: ValueMap) => { const input = { name: values.name, sku: values.sku, category: values.category, price: Number(values.price), stock: Number(values.stock), locationId: locationId ?? undefined }; editing ? update.mutate({ id: editing.id, ...input }) : create.mutate(input); };
  return <div className="workspace-page"><PageHeader eyebrow="Catalog control" title="Product manager" detail="Create, update, and remove sellable items with persistent stock and pricing." actions={<><button className="soft-button" onClick={() => toast("Import started", { description: "Choose a CSV file to begin a guided product import." })}><Upload /> Import</button><Button className="dark-action" onClick={startCreate}><Plus /> Add product</Button></>} /><div className="metric-strip panel-reveal"><MiniMetric label="Active products" value={String(items.length)} trend="Live catalog records" /><MiniMetric label="Low-stock items" value={String(items.filter((item) => item.stock < 15).length)} trend="Requires attention" tone="amber" /><MiniMetric label="Catalog health" value={items.length ? "100%" : "—"} trend="Records ready to sell" tone="blue" /></div><Surface title="All products" kicker={`${items.length} active item${items.length === 1 ? "" : "s"}`} action={<div className="surface-tools"><label className="inline-search"><Search /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search catalog" /></label><button className="icon-surface-button" aria-label="Filter products"><Filter /></button></div>}>{productQuery.isLoading ? <LoadingState /> : <><div className="table-scroll"><table className="workspace-table"><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th /></tr></thead><tbody>{shown.map((product) => <tr key={product.id}><td><span className="table-product"><ProductArt product={product} /><b>{product.name}</b></span></td><td>{product.sku}</td><td>{product.category}</td><td>{money(product.price)}</td><td>{product.stock} units</td><td><StatusPill tone={product.stock < 15 ? "amber" : "green"}>{product.stock < 15 ? "Low stock" : "Active"}</StatusPill></td><td><span className="row-actions"><button className="row-action" aria-label={`Edit ${product.name}`} onClick={() => startEdit(product)}><Pencil /></button><button className="row-action row-action--danger" aria-label={`Delete ${product.name}`} onClick={() => removeRecord(product.name, () => remove.mutate({ id: product.id }))}><Trash2 /></button></span></td></tr>)}</tbody></table></div>{!shown.length ? <EmptyState label="No products found" description="Use Add product to create the first catalog record." /> : <button className="view-all-button" onClick={() => navigate("/inventory")}>Review stock manager <ArrowUpRight /></button>}</>}</Surface>{open ? <EntityDialog key={editing?.id ?? "new-product"} open={open} onOpenChange={setOpen} title={editing ? "Edit product" : "Add product"} detail="Saved products are available immediately across the POS." fields={productFields} initial={editing ? { name: editing.name, sku: editing.sku, category: editing.category, price: editing.price, stock: String(editing.stock) } : {}} onSubmit={submit} submitting={create.isPending || update.isPending} /> : null}</div>;
}

const saleFields: DialogField[] = [{ key: "receiptNumber", label: "Receipt number", placeholder: "S-10001" }, { key: "customerName", label: "Customer", placeholder: "Walk-in customer" }, { key: "channel", label: "Channel", options: ["Retail", "Online"] }, { key: "amount", label: "Amount (EUR)", type: "number", placeholder: "0.00" }, { key: "status", label: "Status", options: ["Pending", "Paid", "Refunded"] }];
const purchaseFields: DialogField[] = [{ key: "purchaseNumber", label: "Purchase order", placeholder: "P-20001" }, { key: "supplierName", label: "Supplier", placeholder: "Supplier name" }, { key: "amount", label: "Amount (EUR)", type: "number", placeholder: "0.00" }, { key: "deliveryStatus", label: "Delivery status", options: ["Receiving", "Delivered", "In transit"] }, { key: "paymentStatus", label: "Payment status", options: ["Open", "Paid"] }];

export function SalesPage() {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<null | { id: number; receiptNumber: string; customerName: string; channel: "Retail" | "Online"; amount: string; status: "Pending" | "Paid" | "Refunded" }>(null); const { activeShopId: locationId } = useShop(); const salesQuery = trpc.sales.list.useQuery(locationId ? { locationId } : undefined); const utils = trpc.useUtils();
  const create = trpc.sales.create.useMutation({ onSuccess: () => { utils.sales.list.invalidate(); setOpen(false); toast("Sale created", { description: "The transaction has been saved." }); } }); const update = trpc.sales.update.useMutation({ onSuccess: () => { utils.sales.list.invalidate(); setOpen(false); setEditing(null); toast("Sale updated", { description: "The transaction has been updated." }); } }); const remove = trpc.sales.remove.useMutation({ onSuccess: () => { utils.sales.list.invalidate(); toast("Sale deleted", { description: "The transaction has been removed." }); } });
  const rows = salesQuery.data ?? []; const gross = rows.filter((row) => row.status === "Paid").reduce((sum, row) => sum + Number(row.amount), 0);
  const submit = (values: ValueMap) => { const input = { receiptNumber: values.receiptNumber, customerName: values.customerName, channel: values.channel as "Retail" | "Online", amount: Number(values.amount), status: values.status as "Pending" | "Paid" | "Refunded", locationId: locationId ?? undefined }; editing ? update.mutate({ id: editing.id, ...input }) : create.mutate(input); };
  return <div className="workspace-page"><PageHeader eyebrow="Revenue ledger" title="Sales" detail="Create, correct, or remove retail and online transactions." actions={<Button className="dark-action" onClick={() => { setEditing(null); setOpen(true); }}><Plus /> New sale</Button>} /><div className="metric-strip panel-reveal"><MiniMetric label="Gross sales" value={money(gross)} trend="Paid sales on file" /><MiniMetric label="Transactions" value={String(rows.length)} trend="Persistent sale records" tone="blue" /><MiniMetric label="Refunded" value={String(rows.filter((row) => row.status === "Refunded").length)} trend="Review as needed" tone="amber" /></div><Surface title="Recent sales" kicker="Live transaction register" action={<label className="inline-search"><Search /><Input placeholder="Search sales" /></label>}>{salesQuery.isLoading ? <LoadingState /> : rows.length ? <div className="table-scroll"><table className="workspace-table"><thead><tr><th>Sale</th><th>Customer</th><th>Date</th><th>Channel</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.receiptNumber}</b></td><td>{row.customerName}</td><td>{dateLabel(row.soldAt)}</td><td>{row.channel}</td><td><b>{money(row.amount)}</b></td><td><StatusPill tone={row.status === "Paid" ? "green" : row.status === "Refunded" ? "red" : "amber"}>{row.status}</StatusPill></td><td><span className="row-actions"><button className="row-action" onClick={() => { setEditing({ id: row.id, receiptNumber: row.receiptNumber, customerName: row.customerName, channel: row.channel, amount: String(row.amount), status: row.status }); setOpen(true); }}><Pencil /></button><button className="row-action row-action--danger" onClick={() => removeRecord(row.receiptNumber, () => remove.mutate({ id: row.id }))}><Trash2 /></button></span></td></tr>)}</tbody></table></div> : <EmptyState label="No sales yet" description="Take a payment in POS or create a manual sale here." />}</Surface>{open ? <EntityDialog key={editing?.id ?? "new-sale"} open={open} onOpenChange={setOpen} title={editing ? "Edit sale" : "Create sale"} detail="All changes are stored in the live revenue ledger." fields={saleFields} initial={editing ?? { channel: "Retail", status: "Paid" }} onSubmit={submit} submitting={create.isPending || update.isPending} /> : null}</div>;
}

export function PurchasesPage() {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<null | { id: number; purchaseNumber: string; supplierName: string; amount: string; deliveryStatus: "Receiving" | "Delivered" | "In transit"; paymentStatus: "Open" | "Paid" }>(null); const { activeShopId: locationId } = useShop(); const purchaseQuery = trpc.purchases.list.useQuery(locationId ? { locationId } : undefined); const utils = trpc.useUtils();
  const create = trpc.purchases.create.useMutation({ onSuccess: () => { utils.purchases.list.invalidate(); setOpen(false); toast("Purchase created", { description: "The supplier commitment has been saved." }); } }); const update = trpc.purchases.update.useMutation({ onSuccess: () => { utils.purchases.list.invalidate(); setOpen(false); setEditing(null); toast("Purchase updated", { description: "Delivery and payment details are saved." }); } }); const remove = trpc.purchases.remove.useMutation({ onSuccess: () => { utils.purchases.list.invalidate(); toast("Purchase deleted", { description: "The purchase order was removed." }); } });
  const rows = purchaseQuery.data ?? []; const total = rows.reduce((sum, row) => sum + Number(row.amount), 0);
  const submit = (values: ValueMap) => { const input = { purchaseNumber: values.purchaseNumber, supplierName: values.supplierName, amount: Number(values.amount), deliveryStatus: values.deliveryStatus as "Receiving" | "Delivered" | "In transit", paymentStatus: values.paymentStatus as "Open" | "Paid", locationId: locationId ?? undefined }; editing ? update.mutate({ id: editing.id, ...input }) : create.mutate(input); };
  return <div className="workspace-page"><PageHeader eyebrow="Supplier ledger" title="Purchases" detail="Create, update, and clear supplier orders with real delivery and payment states." actions={<Button className="dark-action" onClick={() => { setEditing(null); setOpen(true); }}><Plus /> New purchase</Button>} /><div className="metric-strip panel-reveal"><MiniMetric label="Purchase spend" value={money(total)} trend="All purchase orders" /><MiniMetric label="Open orders" value={String(rows.filter((row) => row.paymentStatus === "Open").length)} trend="Awaiting payment" tone="blue" /><MiniMetric label="In transit" value={String(rows.filter((row) => row.deliveryStatus === "In transit").length)} trend="Supplier follow-up" tone="amber" /></div><Surface title="Recent purchases" kicker="Live supplier register">{purchaseQuery.isLoading ? <LoadingState /> : rows.length ? <div className="table-scroll"><table className="workspace-table"><thead><tr><th>Purchase order</th><th>Supplier</th><th>Date</th><th>Delivery</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.purchaseNumber}</b></td><td>{row.supplierName}</td><td>{dateLabel(row.orderedAt)}</td><td>{row.deliveryStatus}</td><td><b>{money(row.amount)}</b></td><td><StatusPill tone={row.paymentStatus === "Paid" ? "green" : "amber"}>{row.paymentStatus}</StatusPill></td><td><span className="row-actions"><button className="row-action" onClick={() => { setEditing({ id: row.id, purchaseNumber: row.purchaseNumber, supplierName: row.supplierName, amount: String(row.amount), deliveryStatus: row.deliveryStatus, paymentStatus: row.paymentStatus }); setOpen(true); }}><Pencil /></button><button className="row-action row-action--danger" onClick={() => removeRecord(row.purchaseNumber, () => remove.mutate({ id: row.id }))}><Trash2 /></button></span></td></tr>)}</tbody></table></div> : <EmptyState label="No purchases yet" description="Create a purchase order to begin your supplier ledger." />}</Surface>{open ? <EntityDialog key={editing?.id ?? "new-purchase"} open={open} onOpenChange={setOpen} title={editing ? "Edit purchase" : "Create purchase"} detail="Supplier orders remain editable until they are reconciled." fields={purchaseFields} initial={editing ?? { deliveryStatus: "Receiving", paymentStatus: "Open" }} onSubmit={submit} submitting={create.isPending || update.isPending} /> : null}</div>;
}

export function StockManagerPage() {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<ProductRecord | null>(null); const { activeShopId: locationId } = useShop(); const productQuery = trpc.products.list.useQuery(); const utils = trpc.useUtils(); const update = trpc.inventory.setOnHand.useMutation({ onSuccess: () => { utils.products.list.invalidate(); utils.inventory.movements.invalidate(); utils.dashboard.summary.invalidate(); setOpen(false); toast("Stock updated", { description: "The inventory count and adjustment history have been saved." }); } }); const products = (productQuery.data ?? []).map((product) => ({ ...product, price: String(product.price) }));
  const stockValue = products.reduce((sum, product) => sum + Number(product.price) * product.stock, 0); const low = products.filter((product) => product.stock < 15);
  return <div className="workspace-page"><PageHeader eyebrow="Inventory control" title="Stock manager" detail="Review live stock coverage and update on-hand counts directly." actions={<><button className="soft-button" onClick={() => toast("Stocktake scheduled", { description: "A new stocktake draft is available." })}><ClipboardList /> Stocktake</button><Button className="dark-action" onClick={() => toast("Transfer draft", { description: "Choose origin and destination stores to start a transfer." })}><Truck /> Transfer stock</Button></>} /><div className="metric-strip panel-reveal"><MiniMetric label="Stock value" value={money(stockValue)} trend="Based on live catalog pricing" /><MiniMetric label="At reorder point" value={String(low.length)} trend="Items below 15 units" tone="amber" /><MiniMetric label="Tracked products" value={String(products.length)} trend="Editable on-hand counts" tone="blue" /></div><div className="inventory-layout panel-reveal"><Surface title="Reorder priorities" kicker={`${low.length} products need a decision`}><div className="reorder-list">{productQuery.isLoading ? <LoadingState /> : low.length ? low.map((product) => <div className="reorder-row" key={product.id}><ProductArt product={product} /><div><b>{product.name}</b><span>{product.stock} available · target 15</span><Progress value={Math.min(product.stock / 15 * 100, 100)} /></div><button className="soft-button" onClick={() => { setEditing(product); setOpen(true); }}>Update stock</button></div>) : <EmptyState label="No low-stock products" description="Products below 15 units will appear here." />}</div></Surface><Surface title="Location coverage" kicker="Current stock balance"><div className="location-list">{products.slice(0, 4).map((product) => <div className="location-row" key={product.id}><div><b>{product.name}</b><span>{product.category}</span></div><strong>{product.stock} units</strong></div>)}</div></Surface></div>{open && editing ? <EntityDialog key={editing.id} open={open} onOpenChange={setOpen} title="Update stock" detail={`Set the current on-hand quantity for ${editing.name}.`} fields={[{ key: "stock", label: "Units in stock", type: "number" }]} initial={{ stock: String(editing.stock) }} onSubmit={(values) => update.mutate({ productId: editing.id, quantity: Number(values.stock), locationId: locationId ?? undefined })} submitting={update.isPending} /> : null}</div>;
}

const expenseFields: DialogField[] = [{ key: "description", label: "Expense description", placeholder: "e.g. Downtown utilities" }, { key: "category", label: "Category", placeholder: "e.g. Utilities" }, { key: "amount", label: "Amount (EUR)", type: "number", placeholder: "0.00" }, { key: "status", label: "Approval status", options: ["Pending", "Approved"] }];
export function ExpensesPage() {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<null | { id: number; description: string; category: string; amount: string; status: "Pending" | "Approved" }>(null); const { activeShopId: locationId } = useShop(); const expenseQuery = trpc.expenses.list.useQuery(locationId ? { locationId } : undefined); const utils = trpc.useUtils(); const create = trpc.expenses.create.useMutation({ onSuccess: () => { utils.expenses.list.invalidate(); setOpen(false); toast("Expense created", { description: "The operating cost is now in your ledger." }); } }); const update = trpc.expenses.update.useMutation({ onSuccess: () => { utils.expenses.list.invalidate(); setOpen(false); setEditing(null); toast("Expense updated", { description: "The expense entry was updated." }); } }); const remove = trpc.expenses.remove.useMutation({ onSuccess: () => { utils.expenses.list.invalidate(); toast("Expense deleted", { description: "The expense entry was removed." }); } });
  const rows = expenseQuery.data ?? []; const total = rows.reduce((sum, row) => sum + Number(row.amount), 0); const submit = (values: ValueMap) => { const input = { description: values.description, category: values.category, amount: Number(values.amount), status: values.status as "Pending" | "Approved", locationId: locationId ?? undefined }; editing ? update.mutate({ id: editing.id, ...input }) : create.mutate(input); };
  return <div className="workspace-page"><PageHeader eyebrow="Operating costs" title="Expenses" detail="Capture, approve, correct, and remove business expenses with a live audit trail." actions={<Button className="dark-action" onClick={() => { setEditing(null); setOpen(true); }}><Plus /> Add expense</Button>} /><div className="metric-strip panel-reveal"><MiniMetric label="Expense total" value={money(total)} trend="All saved expense records" /><MiniMetric label="Awaiting approval" value={String(rows.filter((row) => row.status === "Pending").length)} trend="Requires review" tone="amber" /><MiniMetric label="Approved costs" value={String(rows.filter((row) => row.status === "Approved").length)} trend="Ready to reconcile" tone="blue" /></div><Surface title="Expense activity" kicker="Current period">{expenseQuery.isLoading ? <LoadingState /> : rows.length ? <div className="table-scroll"><table className="workspace-table"><thead><tr><th>Description</th><th>Category</th><th>Date</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><b>{row.description}</b></td><td>{row.category}</td><td>{dateLabel(row.expenseDate)}</td><td><b>{money(row.amount)}</b></td><td><StatusPill tone={row.status === "Approved" ? "green" : "amber"}>{row.status}</StatusPill></td><td><span className="row-actions"><button className="row-action" onClick={() => { setEditing({ id: row.id, description: row.description, category: row.category, amount: String(row.amount), status: row.status }); setOpen(true); }}><Pencil /></button><button className="row-action row-action--danger" onClick={() => removeRecord(row.description, () => remove.mutate({ id: row.id }))}><Trash2 /></button></span></td></tr>)}</tbody></table></div> : <EmptyState label="No expenses recorded" description="Add the first operating cost to start tracking spending." />}</Surface>{open ? <EntityDialog key={editing?.id ?? "new-expense"} open={open} onOpenChange={setOpen} title={editing ? "Edit expense" : "Add expense"} detail="Expense records are saved to the live operating-cost ledger." fields={expenseFields} initial={editing ?? { status: "Pending" }} onSubmit={submit} submitting={create.isPending || update.isPending} /> : null}</div>;
}

export function CashBankPage() { return <div className="workspace-page"><PageHeader eyebrow="Liquidity control" title="Cash & bank" detail="Reconcile every cash drawer, bank account, and settlement balance." actions={<Button className="dark-action" onClick={() => toast("Transfer draft opened", { description: "Complete the transaction details to continue." })}><Plus /> Transfer funds</Button>} /><div className="metric-strip panel-reveal"><MiniMetric label="Available balance" value="€162,945" trend="Across 4 accounts" /><MiniMetric label="Unreconciled" value="5" trend="Requires review" tone="amber" /><MiniMetric label="Next payout" value="€12,418" trend="Scheduled this week" tone="blue" /></div><div className="finance-layout panel-reveal"><Surface title="Account balances" kicker="Live settlement overview"><div className="ledger-list">{[{ title: "TradeCore Business", sub: "Primary account · Updated 2m ago", value: "€96,245.15", tone: "green" }, { title: "Downtown cash drawer", sub: "Counter 02 · Updated 5m ago", value: "€12,840.00", tone: "green" }, { title: "Online settlements", sub: "Processor reserve · Updated 18m ago", value: "€53,860.04", tone: "blue" }].map((entry) => <div className="ledger-row" key={entry.title}><span className={`ledger-icon ledger-icon--${entry.tone}`}><Landmark /></span><div><b>{entry.title}</b><span>{entry.sub}</span></div><strong>{entry.value}</strong></div>)}</div></Surface><Surface title="Cashflow controls" kicker="Account preferences"><div className="control-list">{["Require manager approval over €1,000", "Notify on cash variance", "Daily settlement summary", "Auto-match bank statements"].map((item, index) => <div className="control-row" key={item}><span>{item}</span><Switch defaultChecked={index !== 1} /></div>)}</div></Surface></div></div>; }

const staffFields: DialogField[] = [{ key: "name", label: "Staff member name", placeholder: "Full name" }, { key: "email", label: "Email", type: "email", placeholder: "name@company.com" }, { key: "role", label: "Role", placeholder: "e.g. Sales associate" }, { key: "location", label: "Location", placeholder: "e.g. Downtown" }, { key: "status", label: "Account status", options: ["Active", "Invited", "Inactive"] }];
export function StaffPage() {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<null | { id: number; name: string; email: string; role: string; location: string; status: "Active" | "Invited" | "Inactive" }>(null); const { activeShopId: locationId, activeShop } = useShop(); const staffQuery = trpc.staff.list.useQuery(locationId ? { locationId } : undefined); const utils = trpc.useUtils(); const create = trpc.staff.create.useMutation({ onSuccess: () => { utils.staff.list.invalidate(); setOpen(false); toast("Team member created", { description: "The staff record is now active in TradeCore." }); } }); const update = trpc.staff.update.useMutation({ onSuccess: () => { utils.staff.list.invalidate(); setOpen(false); setEditing(null); toast("Staff member updated", { description: "The team record was updated." }); } }); const remove = trpc.staff.remove.useMutation({ onSuccess: () => { utils.staff.list.invalidate(); toast("Staff member deleted", { description: "The team record was removed." }); } }); const rows = staffQuery.data ?? [];
  const submit = (values: ValueMap) => { const input = { name: values.name, email: values.email, role: values.role, location: activeShop?.name ?? values.location, status: values.status as "Active" | "Invited" | "Inactive", locationId: locationId ?? undefined }; editing ? update.mutate({ id: editing.id, ...input }) : create.mutate(input); };
  return <div className="workspace-page"><PageHeader eyebrow="Team operations" title="Staff members" detail="Invite, update, and remove staff access records across the retail operation." actions={<Button className="dark-action" onClick={() => { setEditing(null); setOpen(true); }}><Plus /> Invite team member</Button>} /><div className="metric-strip panel-reveal"><MiniMetric label="Team records" value={String(rows.length)} trend="Persistent staff directory" /><MiniMetric label="Active today" value={String(rows.filter((row) => row.status === "Active").length)} trend="Active account records" tone="blue" /><MiniMetric label="Pending invites" value={String(rows.filter((row) => row.status === "Invited").length)} trend="Requires follow-up" tone="amber" /></div><Surface title="Team directory" kicker={`${rows.length} staff record${rows.length === 1 ? "" : "s"}`} action={<label className="inline-search"><Search /><Input placeholder="Search staff" /></label>}>{staffQuery.isLoading ? <LoadingState /> : rows.length ? <div className="staff-grid">{rows.map((member) => <article className="staff-card" key={member.id}><span className={`staff-avatar staff-avatar--${member.status === "Active" ? "green" : member.status === "Invited" ? "amber" : "red"}`}>{member.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><div><b>{member.name}</b><span>{member.role} · {member.email}</span></div><StatusPill tone={member.status === "Active" ? "green" : member.status === "Invited" ? "amber" : "red"}>{member.location}</StatusPill><span className="row-actions"><button className="row-action" onClick={() => { setEditing({ id: member.id, name: member.name, email: member.email, role: member.role, location: member.location, status: member.status }); setOpen(true); }}><Pencil /></button><button className="row-action row-action--danger" onClick={() => removeRecord(member.name, () => remove.mutate({ id: member.id }))}><Trash2 /></button></span></article>)}</div> : <EmptyState label="No team members yet" description="Invite the first team member to create a staff access record." />}</Surface>{open ? <EntityDialog key={editing?.id ?? "new-staff"} open={open} onOpenChange={setOpen} title={editing ? "Edit staff member" : "Invite staff member"} detail="Staff records are saved to the TradeCore team directory." fields={staffFields} initial={editing ?? { status: "Invited" }} onSubmit={submit} submitting={create.isPending || update.isPending} /> : null}</div>;
}

const orderFields: DialogField[] = [{ key: "orderNumber", label: "Order number", placeholder: "O-2901" }, { key: "buyerName", label: "Customer", placeholder: "Customer name" }, { key: "itemCount", label: "Item count", type: "number", placeholder: "1" }, { key: "total", label: "Order total (EUR)", type: "number", placeholder: "0.00" }, { key: "fulfilmentMethod", label: "Fulfilment method", options: ["Delivery", "Pickup"] }, { key: "status", label: "Order status", options: ["New", "Ready", "Dispatched", "Cancelled"] }];
export function OrdersPage() {
  const [filter, setFilter] = useState("All"); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<null | { id: number; orderNumber: string; buyerName: string; itemCount: number; total: string; fulfilmentMethod: "Delivery" | "Pickup"; status: "New" | "Ready" | "Dispatched" | "Cancelled" }>(null); const { activeShopId: locationId } = useShop(); const orderQuery = trpc.orders.list.useQuery(locationId ? { locationId } : undefined); const utils = trpc.useUtils(); const create = trpc.orders.create.useMutation({ onSuccess: () => { utils.orders.list.invalidate(); setOpen(false); toast("Order created", { description: "The online order was added to the fulfilment queue." }); } }); const update = trpc.orders.update.useMutation({ onSuccess: () => { utils.orders.list.invalidate(); setOpen(false); setEditing(null); toast("Order updated", { description: "The fulfilment state was saved." }); } }); const remove = trpc.orders.remove.useMutation({ onSuccess: () => { utils.orders.list.invalidate(); toast("Order deleted", { description: "The order was removed from the queue." }); } });
  const rows = orderQuery.data ?? []; const visible = filter === "All" ? rows : rows.filter((row) => row.status === filter); const submit = (values: ValueMap) => { const input = { orderNumber: values.orderNumber, buyerName: values.buyerName, itemCount: Number(values.itemCount), total: Number(values.total), fulfilmentMethod: values.fulfilmentMethod as "Delivery" | "Pickup", status: values.status as "New" | "Ready" | "Dispatched" | "Cancelled", locationId: locationId ?? undefined }; editing ? update.mutate({ id: editing.id, ...input }) : create.mutate(input); };
  return <div className="workspace-page"><PageHeader eyebrow="Digital commerce" title="Online orders" detail="Create and manage the live fulfilment queue for digital orders." actions={<Button className="dark-action" onClick={() => { setEditing(null); setOpen(true); }}><Plus /> Add online order</Button>} /><div className="order-summary panel-reveal"><MiniMetric label="New orders" value={String(rows.filter((row) => row.status === "New").length)} trend="Awaiting acceptance" /><MiniMetric label="Ready for pickup" value={String(rows.filter((row) => row.status === "Ready").length)} trend="Across active locations" tone="blue" /><MiniMetric label="Dispatched" value={String(rows.filter((row) => row.status === "Dispatched").length)} trend="Completed workflow" tone="amber" /></div><Surface title="Fulfilment queue" kicker="Persistent order records" action={<div className="filter-tabs">{["All", "New", "Ready", "Dispatched"].map((item) => <button className={filter === item ? "filter-tab filter-tab--active" : "filter-tab"} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div>}>{orderQuery.isLoading ? <LoadingState /> : visible.length ? <div className="order-list">{visible.map((order) => <div className="order-row" key={order.id}><span className="order-badge"><ShoppingBag /></span><div><b>{order.orderNumber} · {order.buyerName}</b><span>{order.itemCount} item{order.itemCount > 1 ? "s" : ""} · {order.fulfilmentMethod}</span></div><strong>{money(order.total)}</strong><StatusPill tone={order.status === "New" ? "amber" : order.status === "Dispatched" ? "blue" : "green"}>{order.status}</StatusPill><span className="row-actions"><button className="row-action" onClick={() => { setEditing({ id: order.id, orderNumber: order.orderNumber, buyerName: order.buyerName, itemCount: order.itemCount, total: String(order.total), fulfilmentMethod: order.fulfilmentMethod, status: order.status }); setOpen(true); }}><Pencil /></button><button className="row-action row-action--danger" onClick={() => removeRecord(order.orderNumber, () => remove.mutate({ id: order.id }))}><Trash2 /></button></span></div>)}</div> : <EmptyState label="No online orders" description="Add an online order to start the fulfilment queue." />}</Surface>{open ? <EntityDialog key={editing?.id ?? "new-order"} open={open} onOpenChange={setOpen} title={editing ? "Edit online order" : "Add online order"} detail="Order state is saved directly to the live fulfilment queue." fields={orderFields} initial={editing ? { ...editing, itemCount: String(editing.itemCount), total: editing.total } : { fulfilmentMethod: "Pickup", status: "New", itemCount: "1" }} onSubmit={submit} submitting={create.isPending || update.isPending} /> : null}</div>;
}

export function ReportsPage() { const reportCards = [{ title: "Sales performance", sub: "Revenue, margin, and tender mix", icon: ReceiptText, color: "amber" }, { title: "Inventory velocity", sub: "Sell-through, stock turn, and reorders", icon: Boxes, color: "green" }, { title: "Customer cohorts", sub: "Repeat visits and lifetime value", icon: UsersRound, color: "blue" }, { title: "Cash reconciliation", sub: "Drawer variances and settlements", icon: WalletCards, color: "red" }]; return <div className="workspace-page"><PageHeader eyebrow="Business intelligence" title="Reports" detail="Turn transaction data into decisions your retail team can act on." actions={<><button className="soft-button" onClick={() => toast("Report schedule", { description: "Choose a frequency and recipients for scheduled reporting." })}><CalendarDays /> Schedule</button><Button className="dark-action" onClick={() => toast("Report builder", { description: "A custom report canvas is ready to configure." })}><Plus /> Create report</Button></>} /><div className="report-grid panel-reveal">{reportCards.map(({ title, sub, icon: Icon, color }) => <article className="report-card" key={title}><span className={`report-icon report-icon--${color}`}><Icon /></span><p className="card-kicker">Saved report</p><h2>{title}</h2><span>{sub}</span><button onClick={() => toast(title, { description: "The selected report is ready to run." })}>Run report <ArrowUpRight /></button></article>)}</div><Surface title="Scheduled reporting" kicker="Automated business updates"><div className="schedule-list">{[{ title: "Weekly trading summary", sub: "Every Monday · 08:00", receivers: "Sandy Kline, Finance" }, { title: "Low-stock digest", sub: "Every weekday · 07:30", receivers: "Store managers" }, { title: "Month-end close", sub: "1st day of month · 09:00", receivers: "Finance team" }].map((schedule) => <div className="schedule-row" key={schedule.title}><FileBarChart /><div><b>{schedule.title}</b><span>{schedule.sub} · {schedule.receivers}</span></div><button className="soft-button" onClick={() => toast("Schedule updated", { description: `${schedule.title} is open for editing.` })}><Pencil /> Edit</button></div>)}</div></Surface></div>; }

export function WebsiteSetupPage() { return <div className="workspace-page"><PageHeader eyebrow="Digital presence" title="Website setup" detail="Keep your storefront consistent with the TradeCore catalog and brand." actions={<Button className="dark-action" onClick={() => toast("Site published", { description: "Your current storefront changes are now live." })}><Globe2 /> Publish changes</Button>} /><div className="website-layout panel-reveal"><Surface title="Storefront preview" kicker="Live catalog experience" className="site-preview-surface"><div className="site-preview"><div className="preview-nav"><b>Trade<span>Core</span></b><small>Shop · About · Contact</small></div><div className="preview-hero"><p>SMART RETAIL, SIMPLIFIED</p><h3>Goods that keep your day moving.</h3><button>Shop collection</button></div><div className="preview-product-row"><span>Featured items</span><div><i /><i /><i /></div></div></div></Surface><Surface title="Launch checklist" kicker="3 of 5 completed" className="site-checklist-surface"><div className="launch-list">{[{ task: "Connect your custom domain", done: true }, { task: "Review payment and delivery options", done: true }, { task: "Publish the first collection", done: true }, { task: "Add legal and contact information", done: false }, { task: "Invite storefront manager", done: false }].map((task) => <button className={task.done ? "launch-item launch-item--done" : "launch-item"} key={task.task} onClick={() => toast(task.done ? "Completed" : "Checklist item", { description: task.task })}><span>{task.done ? <Check /> : null}</span><b>{task.task}</b>{task.done ? null : <ChevronDown />}</button>)}</div></Surface></div></div>; }

export function SettingsPage() { const [notifications, setNotifications] = useState(true); const [taxes, setTaxes] = useState(true); const [offline, setOffline] = useState(false); return <div className="workspace-page"><PageHeader eyebrow="Workspace controls" title="Settings" detail="Configure the operational defaults that keep every location in sync." actions={<Button className="dark-action" onClick={() => toast("Settings saved", { description: "Your operational preferences have been updated." })}><Check /> Save changes</Button>} /><div className="settings-layout panel-reveal"><Surface title="Workspace profile" kicker="General"><div className="settings-form"><label>Business name<Input defaultValue="TradeCore Retail Group" /></label><label>Primary email<Input defaultValue="operations@tradecore.co" /></label><label>Default location<div className="select-like">Downtown <ChevronDown /></div></label><label>Currency<div className="select-like">EUR · Euro <ChevronDown /></div></label></div></Surface><Surface title="Operational preferences" kicker="Controls"><div className="preference-list"><div><span><Bell /><b>Daily operational notifications</b><small>Receive a concise summary of sales, stock, and cashflow.</small></span><Switch checked={notifications} onCheckedChange={setNotifications} /></div><div><span><Tag /><b>Automatic tax calculation</b><small>Apply default product tax at the point of sale.</small></span><Switch checked={taxes} onCheckedChange={setTaxes} /></div><div><span><Store /><b>Offline register mode</b><small>Allow counter sales while the network is unavailable.</small></span><Switch checked={offline} onCheckedChange={setOffline} /></div></div></Surface></div></div>; }
